### ISSUE TITLE
Enhancement - example 

### ISSUE THREAD

**Issue by johndpope** [KevinVitale/ReactiveJSON#8]
I did find this
https://github.com/celiaelia/MyPhotosAlbum

It might be worthwhile looking into this -> 
https://github.com/cookiecutter-swift/Framework

it will update the library to target specific platforms.
<img width="542" alt="screen shot 2016-11-29 at 14 17 45" src="https://cloud.githubusercontent.com/assets/289994/20725006/75ca4566-b63e-11e6-87e4-da2f67a23d68.png">

Also - there doesn't appear to be a workspace file here - this is the first library I've needed to build with carthage so it's not so simple to pin point why dependencies ReactiveCocoa are failing.
Was there a reason why cocoapods wasn't used? 
I drafted a podspec - https://github.com/johndpope/ReactiveJSON/blob/master/ReactiveJSON.podspec
which has the necessary dependencies - but there's something missing from project file.

**Comment by KevinVitale** [comment]
@johndpope: thanks for the note. I don't intend to support Cocoapods myself; Carthage and Cocoapods can work alongside each other, if you're already using the latter in your workspace file.

After running `carthage install --platform iOS`, you should have a built `ReactiveJSON.framework` bundle that can be dragged into Xcode and linked with your primary application target.

If you're trying to deploy your application to a device (instead of a simulator), the carthage comes with a CLI command that can copy necessary dependencies to your final app bundle — instructions are on their _README_, (often takes just a few seconds).
